### ISSUE TITLE
Doesn't read anything (and node stop after 5 sec)

### ISSUE THREAD

**Issue by PierreTrp** [mitchellparsons/rc522-rfid-promise#4]
I followed the instructions carefully, created a file `app.js` in `/bcm2835-1.35` pasted the following code in it

```
var rc522 = require("rc522-rfid-promise");

rc522.startListening(5000)
	.then(function(rfidTag){
    	console.log(rfidTag);
	});
```
and launched it with `node app.js`

But the reader doesn't read anything and after 5 sec node stop. 

Any ideas?

I added a setInterval to prevent node from stopping, **but the reader doesn't seems to read anything (it works with a similar python script, but i need to use node for this project):**

```
setInterval(function(){
console.log(1);
},1000);

```

Note : i have the same RFID reader than you and a Raspberry 3 B

![img_2060](https://user-images.githubusercontent.com/3466281/38769066-416882b6-3ffd-11e8-9068-29638a167a53.JPG)

**Comment by mitchellparsons** [comment]
Unfortunately It has been a couple years when I got my board working, and I believe I used the Raspberry pi 2 when I did this.

I do recall having issues with the SPI interface and making sure its enabled properly.  Check out something like this https://pimylifeup.com/raspberry-pi-rfid-rc522/ and maybe even try it in python first to make sure it works.

I cant really help more than that I'm afraid. Good luck!

**Comment by PierreTrp** [comment]
Thanks, i tried in python and it works great, but for that i had to download [SPI-Py](https://github.com/lthiery/SPI-Py), unfortunately it's not available for node

EDIT : i ended up using https://www.npmjs.com/package/MFRC522-node which work fine ! Thanks for you time anyway :)
